keys:
  - &admin_marenz1 069836A578F7939612DB4934F77D0F7E247A1EE4
  - &admin_marenz2 ED06986DFAAE6A61B751DC2F537F97DFB394C433
  - &marenz-frickelkiste age1vk2v0wk4g4uym54f7ldjrugwe86qhlu28dektp7cjlldadqrrg7sdze6x9
  - &wg-bar-ma age1xwszjcwnkyshugls5etvqj8kn4jxw3q53cynfg9ufrma6m7vnywsvpp2lk
  - &controller-physec age153yu8l7wdx6e7zs63pvwrpzzqmljz5tp5ucx6yzxqs62n9wynvuq5czkqt
  - &gitlab-runner-docker age1j35a2gpr9e22gf966xj3mfu03h87nvy0nfgf7edgc65vcf8de4sqmp7xhf
  - &cal-marenz age14mta5a24a4xj0erlvhq4l7yn47ww59glxp2du9mdz5cscrkyf3asp7tdu7

creation_rules:
  - path_regex: secrets/[^/]+\.*$
    key_groups:
      - pgp:
        - *admin_marenz1
        - *admin_marenz2
  - path_regex: secrets/marenz-frickelkiste/[^/]+\.*$
    key_groups:
      - pgp:
        - *admin_marenz1
        - *admin_marenz2
        age:
        - *marenz-frickelkiste
  - path_regex: secrets/wg-bar-ma/[^/]+\.*$
    key_groups:
      - pgp:
        - *admin_marenz1
        - *admin_marenz2
        age:
        - *wg-bar-ma
  - path_regex: secrets/controller-physec/[^/]+\.*$
    key_groups:
      - pgp:
        - *admin_marenz1
        - *admin_marenz2
        age:
        - *controller-physec
  - path_regex: secrets/gitlab-runner-docker/[^/]+\.*$
    key_groups:
      - pgp:
        - *admin_marenz1
        - *admin_marenz2
        age:
        - *gitlab-runner-docker
  - path_regex: secrets/cal-marenz/[^/]+\.*$
    key_groups:
      - pgp:
        - *admin_marenz1
        - *admin_marenz2
        age:
        - *cal-marenz
