# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  boot.initrd.availableKernelModules = [ "ata_piix" "ahci" "vmw_pvscsi" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d3ae48ea-4372-42ee-8a80-62f03ae9c443";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/806cad44-99fb-41b0-bc8b-3910fb4f50fa"; }];

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
